title: "Editor Hallo \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Schrijf een interactief Python-project dat emoji gebruikt
meta_title: Python programmeerprojecten voor kinderen en tieners | Hallo wereld
meta_description: Leer Python met de Raspberry Pi Foundation. Maak een interactief Python programmeerproject dat emoji's gebruikt.
version: 4
listed: true
copyedit: false
last_tested: "2021-10-06"
landing: true
steps:
  - 
    title: Print Hello
  - 
    title: Variabelen
    completion:
      - engaged
  - 
    title: Variabelen afdrukken
  - 
    title: Een andere variabele afdrukken
  - 
    title: Operatoren
  - 
    title: Maak een berekening
  - 
    title: Modules gebruiken
  - 
    title: Druk de datum af
  - 
    title: Functies
  - 
    title: Gooi dobbelstenen
  - 
    title: Importeer randint
  - 
    title: Willekeurige getallen
  - 
    title: Tekenreeksen vermenigvuldigen
  - 
    title: Invoer ophalen
  - 
    title: Verander de dobbelstenen
    completion:
      - internal
  - 
    title: Nu ben jij aan de beurt
    completion:
      - external
