title: "Editor Hello \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Write an interactive Python project that uses emoji
meta_title: Python coding projects for kids and teens | Hello world
meta_description: Learn Python with the Raspberry Pi Foundation. Make an interactive Python coding project that uses emojis.
version: 4
listed: true
copyedit: false
last_tested: "2021-10-06"
landing: true
steps:
  - title: Print Hello
  - title: Variables
    completion:
      - engaged
  - title: Print variables
  - title: Print another variable
  - title: Operators
  - title: Create a calculation
  - title: Using modules
  - title: Print the date
  - title: Functions
  - title: Roll dice
  - title: Import randint
  - title: Random numbers
  - title: Multiply strings
  - title: Get input
  - title: Change the dice
    completion:
      - internal
  - title: Over to you
    completion:
      - external
