title: "Editeur Bonjour \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Écris un projet Python interactif qui utilise des emojis
meta_title: Projets de codage Python pour enfants et adolescent·e·s | Bonjour le monde
meta_description: Apprends Python avec la Raspberry Pi Foundation. Crée un projet de codage Python interactif qui utilise des emojis.
version: 4
listed: true
copyedit: false
last_tested: "2021-10-06"
landing: true
steps:
  - 
    title: Print Hello
  - 
    title: Variables
    completion:
      - engaged
  - 
    title: Imprimer des variables
  - 
    title: Imprimer une autre variable
  - 
    title: Opérateurs
  - 
    title: Créer un calcul
  - 
    title: Utilisation des modules
  - 
    title: Imprimer la date
  - 
    title: Fonctions
  - 
    title: Lancer un dé
  - 
    title: Importer randint
  - 
    title: Nombres aléatoires
  - 
    title: Multiplier les chaînes
  - 
    title: Obtenir une entrée
  - 
    title: Changer le dé
    completion:
      - internal
  - 
    title: À toi de jouer
    completion:
      - external
